spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.expiration.time=604800000
jwt.secret.key=${JWT_SECRET}
#jwt.secret.key=7a05abf418def3578e2f4f1fbe68606f591cbe669ace04b72f694d6143f65398

storage.base-path=/data/images
storage.public-base-url=https://api-biblioteca.online/uploads